version: '2'
services:
    gateway:
        build: ./API-Gateway/
        ports:
        - "80:80"
        links:
        - service1
        - service2
        networks:
        - public
        - private
        # image: mycontainerregistry-on.azurecr.io/images/demo-gateway
    rabbit:
        image: rabbitmq:3-management
        ports:
        - "8081:15672"
        - "5672:5672"
        networks: 
        - public
        - private
    service1:
        build: ./MicroService-01/
        ports:
        - "4001"
        # image: mycontainerregistry-on.azurecr.io/images/demo-service1
        links:
        - rabbit
        networks:
        - private
    service2:
        build: ./MicroService-02/
        ports:
        - "4002"
        networks:
        - private
        # image: mycontainerregistry-on.azurecr.io/images/demo-service2
    consumer:
        build: ./Consumer/
        ports:
        - "5000"
        links:
        - rabbit
        networks:
        - private
networks:
    public:
    private: